### ISSUE TITLE
Markdown Dependency Fail

### ISSUE THREAD

**Issue by krionical** [nicbou/ursus#1]
```
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
ursus-ssg depends on Markdown@ git+https://github.com/nicbou/markdown.git@nicbou-patch-1
```

This is in response pip install  ursus_ssg on a linux system.

**Comment by nicbou** [comment]
Fixed. It was a temporary patch to fix an issue with the Markdown package. My fix to that package has been merged and released this week, so the patch was no longer needed.

**Comment by krionical** [comment]
Confirmed. Thanks!
