### ISSUE TITLE
Would like to use this for my personal site

### ISSUE THREAD

**Issue by TomGranot** [nicbou/ursus#2]
Would you consider this alpha or should I go ahead? Got a few posts to copy and would like to start writing again :)

**Comment by nicbou** [comment]
Hi Tom,

It has been running in production for almost a year. [All About Berlin](https://allaboutberlin.com/) and [my personal website](https://nicolasbouliane.com/) run on it. I have no plans to phase it out.

The only downsides that I can think of:

- I'm a bit slow at pushing the latest commits as a new release
- The `-f` (fast) mode does not rebuild all pages affected by a content change
- There are probably some quirks and opinionated decisions that I got used to, but that won't make sense to you
